version: '3.8'

services:
  minecraft:
    build: .
    container_name: minecraft_server
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft_data/world:/minecraft/world
    environment:
      - TZ=UTC
    restart: unless-stopped
    tty: true
    stdin_open: true
    user: minecraft
    working_dir: /minecraft
